// Full Korean math curriculum structure
// Each entry: { grade, curriculum, topic, difficultyRange: [min, max] }
// grade: 중1|중2|중3|고1|고2|고3
// curriculum: the main category
// topic: the subcategory

const CURRICULUM = [
  // 중1
  { grade: '중1', curriculum: '수와 연산', topic: '소인수분해' },
  { grade: '중1', curriculum: '수와 연산', topic: '최대공약수·최소공배수' },
  { grade: '중1', curriculum: '수와 연산', topic: '정수와 유리수' },
  { grade: '중1', curriculum: '수와 연산', topic: '유리수의 사칙연산' },
  { grade: '중1', curriculum: '문자와 식', topic: '문자의 사용과 식' },
  { grade: '중1', curriculum: '문자와 식', topic: '일차식의 계산' },
  { grade: '중1', curriculum: '문자와 식', topic: '일차방정식' },
  { grade: '중1', curriculum: '문자와 식', topic: '일차방정식의 활용' },
  { grade: '중1', curriculum: '함수와 그래프', topic: '좌표평면과 그래프' },
  { grade: '중1', curriculum: '함수와 그래프', topic: '정비례와 반비례' },
  { grade: '중1', curriculum: '도형과 측정', topic: '기본 도형' },
  { grade: '중1', curriculum: '도형과 측정', topic: '작도와 합동' },
  { grade: '중1', curriculum: '도형과 측정', topic: '평면도형' },
  { grade: '중1', curriculum: '도형과 측정', topic: '입체도형' },
  { grade: '중1', curriculum: '자료와 가능성', topic: '자료의 정리와 해석' },
  { grade: '중1', curriculum: '자료와 가능성', topic: '대푯값' },
  // 중2
  { grade: '중2', curriculum: '수와 연산', topic: '유리수와 순환소수' },
  { grade: '중2', curriculum: '수와 연산', topic: '지수법칙' },
  { grade: '중2', curriculum: '수와 연산', topic: '단항식·다항식의 계산' },
  { grade: '중2', curriculum: '문자와 식', topic: '일차부등식' },
  { grade: '중2', curriculum: '문자와 식', topic: '연립일차방정식' },
  { grade: '중2', curriculum: '문자와 식', topic: '연립방정식의 활용' },
  { grade: '중2', curriculum: '함수와 그래프', topic: '일차함수와 그래프' },
  { grade: '중2', curriculum: '함수와 그래프', topic: '일차함수의 성질' },
  { grade: '중2', curriculum: '함수와 그래프', topic: '일차함수와 방정식의 관계' },
  { grade: '중2', curriculum: '도형과 측정', topic: '삼각형의 성질' },
  { grade: '중2', curriculum: '도형과 측정', topic: '사각형의 성질' },
  { grade: '중2', curriculum: '도형과 측정', topic: '도형의 닮음' },
  { grade: '중2', curriculum: '도형과 측정', topic: '삼각형의 닮음 조건' },
  { grade: '중2', curriculum: '도형과 측정', topic: '평행선과 선분의 길이의 비' },
  { grade: '중2', curriculum: '도형과 측정', topic: '피타고라스 정리' },
  { grade: '중2', curriculum: '자료와 가능성', topic: '경우의 수' },
  { grade: '중2', curriculum: '자료와 가능성', topic: '확률과 기본 성질' },
  // 중3
  { grade: '중3', curriculum: '수와 연산', topic: '제곱근의 뜻과 성질' },
  { grade: '중3', curriculum: '수와 연산', topic: '무리수와 실수' },
  { grade: '중3', curriculum: '수와 연산', topic: '근호를 포함한 식의 계산' },
  { grade: '중3', curriculum: '문자와 식', topic: '다항식의 곱셈' },
  { grade: '중3', curriculum: '문자와 식', topic: '인수분해' },
  { grade: '중3', curriculum: '문자와 식', topic: '이차방정식' },
  { grade: '중3', curriculum: '문자와 식', topic: '근의 공식' },
  { grade: '중3', curriculum: '문자와 식', topic: '이차방정식의 활용' },
  { grade: '중3', curriculum: '함수와 그래프', topic: '이차함수와 그래프' },
  { grade: '중3', curriculum: '함수와 그래프', topic: '이차함수의 최댓값·최솟값' },
  { grade: '중3', curriculum: '도형과 측정', topic: '삼각비' },
  { grade: '중3', curriculum: '도형과 측정', topic: '삼각비의 활용' },
  { grade: '중3', curriculum: '도형과 측정', topic: '원과 직선' },
  { grade: '중3', curriculum: '도형과 측정', topic: '원주각과 중심각' },
  { grade: '중3', curriculum: '도형과 측정', topic: '원과 비례' },
  { grade: '중3', curriculum: '자료와 가능성', topic: '대푯값과 산포도' },
  { grade: '중3', curriculum: '자료와 가능성', topic: '상관관계' },
  // 고1
  { grade: '고1', curriculum: '문자와 식', topic: '다항식의 연산' },
  { grade: '고1', curriculum: '문자와 식', topic: '나머지정리·인수분해' },
  { grade: '고1', curriculum: '문자와 식', topic: '복소수' },
  { grade: '고1', curriculum: '문자와 식', topic: '이차방정식' },
  { grade: '고1', curriculum: '문자와 식', topic: '고차방정식' },
  { grade: '고1', curriculum: '문자와 식', topic: '연립방정식' },
  { grade: '고1', curriculum: '문자와 식', topic: '절댓값·이차부등식' },
  { grade: '고1', curriculum: '함수와 그래프', topic: '함수·합성함수·역함수' },
  { grade: '고1', curriculum: '함수와 그래프', topic: '유리함수' },
  { grade: '고1', curriculum: '함수와 그래프', topic: '무리함수' },
  { grade: '고1', curriculum: '도형과 측정', topic: '평면좌표' },
  { grade: '고1', curriculum: '도형과 측정', topic: '직선의 방정식' },
  { grade: '고1', curriculum: '도형과 측정', topic: '원의 방정식' },
  { grade: '고1', curriculum: '도형과 측정', topic: '도형의 이동' },
  { grade: '고1', curriculum: '집합과 논리', topic: '집합' },
  { grade: '고1', curriculum: '집합과 논리', topic: '명제' },
  { grade: '고1', curriculum: '집합과 논리', topic: '충분·필요조건' },
  { grade: '고1', curriculum: '집합과 논리', topic: '절대부등식' },
  { grade: '고1', curriculum: '자료와 가능성', topic: '순열' },
  { grade: '고1', curriculum: '자료와 가능성', topic: '조합' },
  { grade: '고1', curriculum: '선형대수', topic: '행렬의 뜻' },
  { grade: '고1', curriculum: '선형대수', topic: '행렬의 덧셈·뺄셈·실수배' },
  { grade: '고1', curriculum: '선형대수', topic: '행렬의 곱셈' },
  // 고2
  { grade: '고2', curriculum: '함수와 그래프', topic: '지수함수' },
  { grade: '고2', curriculum: '함수와 그래프', topic: '로그함수' },
  { grade: '고2', curriculum: '함수와 그래프', topic: '삼각함수 그래프' },
  { grade: '고2', curriculum: '함수와 그래프', topic: '삼각함수의 활용' },
  { grade: '고2', curriculum: '문자와 식', topic: '지수·로그의 연산' },
  { grade: '고2', curriculum: '문자와 식', topic: '일반각·호도법' },
  { grade: '고2', curriculum: '문자와 식', topic: '삼각함수 항등식' },
  { grade: '고2', curriculum: '수열', topic: '등차수열·등비수열' },
  { grade: '고2', curriculum: '수열', topic: '시그마 (∑)' },
  { grade: '고2', curriculum: '수열', topic: '수열의 귀납적 정의' },
  { grade: '고2', curriculum: '수열', topic: '수학적 귀납법' },
  { grade: '고2', curriculum: '함수의 극한과 연속', topic: '함수의 극한값' },
  { grade: '고2', curriculum: '함수의 극한과 연속', topic: '극한의 성질' },
  { grade: '고2', curriculum: '함수의 극한과 연속', topic: '함수의 연속' },
  { grade: '고2', curriculum: '미분', topic: '미분계수' },
  { grade: '고2', curriculum: '미분', topic: '도함수' },
  { grade: '고2', curriculum: '미분', topic: '극값·최댓값·최솟값' },
  { grade: '고2', curriculum: '미분', topic: '방정식·부등식에의 활용' },
  { grade: '고2', curriculum: '미분', topic: '속도·가속도' },
  { grade: '고2', curriculum: '적분', topic: '부정적분' },
  { grade: '고2', curriculum: '적분', topic: '정적분' },
  { grade: '고2', curriculum: '적분', topic: '넓이' },
  { grade: '고2', curriculum: '적분', topic: '속도와 거리' },
  { grade: '고2', curriculum: '경우의 수와 확률', topic: '순열·조합 심화' },
  { grade: '고2', curriculum: '경우의 수와 확률', topic: '이항정리' },
  { grade: '고2', curriculum: '경우의 수와 확률', topic: '확률의 뜻과 활용' },
  { grade: '고2', curriculum: '경우의 수와 확률', topic: '조건부 확률' },
  { grade: '고2', curriculum: '경우의 수와 확률', topic: '독립과 종속' },
  { grade: '고2', curriculum: '통계', topic: '이산·연속 확률분포' },
  { grade: '고2', curriculum: '통계', topic: '이항분포' },
  { grade: '고2', curriculum: '통계', topic: '정규분포' },
  { grade: '고2', curriculum: '통계', topic: '표본평균과 추정' },
  { grade: '고2', curriculum: '통계', topic: '모비율 추정' },
  // 고3
  { grade: '고3', curriculum: '수열의 극한', topic: '수열의 극한값' },
  { grade: '고3', curriculum: '수열의 극한', topic: '급수' },
  { grade: '고3', curriculum: '심화 미분', topic: '지수·로그함수의 미분' },
  { grade: '고3', curriculum: '심화 미분', topic: '삼각함수의 미분' },
  { grade: '고3', curriculum: '심화 미분', topic: '매개변수 미분' },
  { grade: '고3', curriculum: '심화 미분', topic: '음함수 미분' },
  { grade: '고3', curriculum: '심화 미분', topic: '이계도함수' },
  { grade: '고3', curriculum: '심화 적분', topic: '치환적분' },
  { grade: '고3', curriculum: '심화 적분', topic: '부분적분' },
  { grade: '고3', curriculum: '심화 적분', topic: '정적분 심화 활용' },
  { grade: '고3', curriculum: '이차곡선', topic: '포물선' },
  { grade: '고3', curriculum: '이차곡선', topic: '타원' },
  { grade: '고3', curriculum: '이차곡선', topic: '쌍곡선' },
  { grade: '고3', curriculum: '벡터', topic: '벡터의 연산' },
  { grade: '고3', curriculum: '벡터', topic: '벡터의 내적' },
  { grade: '고3', curriculum: '공간도형', topic: '공간도형' },
  { grade: '고3', curriculum: '공간도형', topic: '공간좌표' },
  { grade: '고3', curriculum: '공간도형', topic: '직선과 평면의 방정식' },
]

module.exports = CURRICULUM
